spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uni-rent
    username: dev
    password: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    rest:
      base-path: /api

stripe.secret.key=sk_test_51OOQ7uKHQZnt6NMnsd878BZxi3AXaMskUKkWUyamqJDeu505z1w8TscPhzF5M7Fj6trki99UDiaORbUMU3FbdlaP00oqUdSc54